### ISSUE TITLE
Problem with fastcgi and https.

### ISSUE THREAD

**Issue by smithj4** [cloos/RT-Extension-Gravatar#1]
I was testing this module on our new 4.4.1 RT server we are currently setting up and it works fine with modperl2 because it already has all of the CGI environment variables defined, including HTTPS=on, but when I tried it with Apache's mod_fcgid, that environment variable was missing. I had to add the following line to the RT apache mod_fcgid config:

FcgidInitialEnv HTTPS on

This is because Gravatar.pm:21 only uses the https URL when that variable is defined and set to on, so with fastcgi and when using https, I would get a security verification warning because some content was not verified.

**Comment by netsandbox** [comment]
I released 2.01 which fixes this.
I pushed also the updated version to CPAN, which should appear shortly.
